# Generated by Django 5.0.6 on 2024-07-01 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds_and_strategies', '0003_exchangeaccount'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='balance',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='performancemetric',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='exchangeaccount',
            name='fund',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='fund',
        ),
        migrations.AddField(
            model_name='balance',
            name='strategy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='funds_and_strategies.strategy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exchangeaccount',
            name='strategy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='funds_and_strategies.strategy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='performancemetric',
            name='strategy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='funds_and_strategies.strategy'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='balance',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='performancemetric',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='performancemetric',
            name='version',
        ),
    ]
