# Generated by Django 5.0.6 on 2024-07-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds_and_strategies', '0006_rename_balance_asset_amount_asset_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='exchangeaccount',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
