# Generated by Django 5.0.6 on 2024-07-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds_and_strategies', '0007_balance_last_updated_exchangeaccount_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeaccount',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
