# Generated by Django 5.0.6 on 2024-07-03 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds_and_strategies', '0008_exchangeaccount_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='exchange_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='funds_and_strategies.exchangeaccount'),
            preserve_default=False,
        ),
    ]
