# Generated by Django 5.0.6 on 2024-07-14 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds_and_strategies', '0009_asset_exchange_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('network', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funds_and_strategies.strategy')),
            ],
        ),
    ]
