# Generated by Django 5.0.6 on 2024-07-14 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds_and_strategies', '0012_wallet_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='funds_and_strategies.wallet'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='exchange_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='funds_and_strategies.exchangeaccount'),
        ),
    ]
