# Generated by Django 5.0.6 on 2024-07-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds_and_strategies', '0013_asset_wallet_alter_asset_exchange_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangeaccount',
            name='date_added',
        ),
        migrations.AddField(
            model_name='exchangeaccount',
            name='exchange',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
