# Generated by Django 5.0.6 on 2024-07-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds_and_strategies', '0014_remove_exchangeaccount_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='modified_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
