# Generated by Django 5.0.6 on 2024-07-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds_and_strategies', '0016_alter_asset_date_alter_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='value_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
