# Generated by Django 5.0.6 on 2024-07-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds_and_strategies', '0018_alter_transaction_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='modified_by_user',
        ),
        migrations.AddField(
            model_name='strategy',
            name='manual',
            field=models.BooleanField(default=False),
        ),
    ]
