# Generated by Django 5.0.6 on 2024-07-18 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds_and_strategies', '0020_alter_asset_options_alter_balance_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value_usd', models.DecimalField(decimal_places=2, max_digits=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funds_and_strategies.fund')),
            ],
        ),
    ]
