# Generated by Django 5.0.6 on 2024-07-18 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds_and_strategies', '0021_fundbalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='fund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='funds_and_strategies.fund'),
        ),
        migrations.AddField(
            model_name='performancemetric',
            name='fund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='funds_and_strategies.fund'),
        ),
        migrations.AlterField(
            model_name='balance',
            name='strategy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='funds_and_strategies.strategy'),
        ),
        migrations.AlterField(
            model_name='performancemetric',
            name='strategy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='funds_and_strategies.strategy'),
        ),
        migrations.DeleteModel(
            name='FundBalance',
        ),
    ]
