# Generated by Django 5.0.6 on 2024-07-21 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds_and_strategies', '0022_balance_fund_performancemetric_fund_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.FloatField()),
                ('index_type', models.CharField(choices=[('BTC', 'Bitcoin'), ('BDM', 'Broad Digital Market')], max_length=3)),
            ],
            options={
                'unique_together': {('date', 'index_type')},
            },
        ),
    ]
