# Generated by Django 5.0.6 on 2024-07-22 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funds_and_strategies', '0023_index'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Index',
        ),
    ]
