# Generated by Django 5.0.6 on 2024-08-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds_and_strategies', '0027_performancemetric_value_eur_transaction_value_eur'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='value_eur',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
