# Generated by Django 5.0.6 on 2024-08-23 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds_and_strategies', '0028_balance_value_eur'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('currency', models.CharField(max_length=3)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funds_and_strategies.fund')),
            ],
        ),
    ]
